# Generated by Django 5.2.8 on 2025-11-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('sector', models.CharField(max_length=255)),
                ('energy_consumption_mwh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('co2_emissions_tons', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Emission Record',
                'verbose_name_plural': 'Emission Records',
                'ordering': ['-year', 'company'],
                'unique_together': {('company', 'year')},
            },
        ),
    ]
